### ISSUE TITLE
Add Python 3.13 support

### ISSUE THREAD

**Issue by dmayo3** [dmayo3/mocksafe#64]

**Comment by Brijeshthummar02** [comment]
@dmayo3 can you show me path to repo and files

**Comment by dmayo3** [comment]
Hi @Brijeshthummar02 

Thanks for reaching out.

I'm not sure what you mean about the path to the repo or which files?

If you're looking for files related to Python version compatibility, you'll want to check the following:

pyproject.toml: This file includes details on dependencies and compatible Python versions.

tox.ini: This is used for running tests across different Python environments.

.python-version: Specifies the Python versions for local development.

CI workflows:

* .github/workflows/mocksafe.yml
* .github/workflows/release.yaml

These control our CI pipelines, including which Python versions are used for testing and releases.

Let me know if you need any more help navigating these files or making changes to add Python 3.13 support.
